### ISSUE TITLE
Public repo?

### ISSUE THREAD

**Issue by bsideup** [rbkmoney/newway#78]
Hi!

Are you sure this repo should be private? :)
I mean... I was happy to discover that you use Testcontainers, but wasn't certain that the repo is an actual OSS project 😅

**Comment by antonlva** [comment]
Well, Rome wasn't built in a day. We haven't completed all the documentability tasks yet, but yes, we're sure all the public repos of RBKmoney are public for a reason. As the rest parts of our payments processing platform :)

Thanks for drawing our attention to it anyway!

**Comment by bsideup** [comment]
Impressive! 👍 

Good to know that some big financial companies OSS their platforms :) Cheers!
